### ISSUE TITLE
Mobs are broken

### ISSUE THREAD

**Issue by SCMGamingYT** [2pocket2edition/Nukkit#11]
-Skeletons shoot through walls
-Overpopulation of Hostile mobs
-Non Hostile mobs can only be found in large groups
-much thx

**Comment by DaMatrix** [comment]
Mobs should spawn much less frequently as of f6f56ac0e61d5f9fb73747265c5c3bbb21260c75

Also passive mobs spawning in packs is vanilla behavior.

AI bugginess is something i'm working on

**Comment by SCMGamingYT** [comment]
thanks amigo
