### ISSUE TITLE
Fix Droppers and Dispensers 

### ISSUE THREAD

**Issue by ghost** [2pocket2edition/Nukkit#17]
I didn’t understand the thing so i deleted it all and replaced it with this
Dispensers and droppers will craft but if you try to place them, they disapear and go back to your inventory

**Comment by DaMatrix** [comment]
That's part of the whole "implement redstone" task, which is something i've delayed for a later date.

**Comment by ghost** [comment]
Apologies.. I didn’t think of the redstone aspect of it, I was more concerned about storage.
