### ISSUE TITLE
Noticeable bugs

### ISSUE THREAD

**Issue by xyzvp3935** [2pocket2edition/Nukkit#2]
### Expected Behavior

Normal mobs (hostile & passive).
2. Stacking up - Being able to stack up blocks for protection.

### Actual Behavior

Travel at an alarming rate, and take twice the amount of damage to kill.
2. Stacking - Will display you have stacked up, then take you back down and kick you for flying.

### Debug information

* Debug link:
* Timings link (if relevant):

**Comment by DaMatrix** [comment]
should be fixed, will be live after i restart server.
