### ISSUE TITLE
Portal coords

### ISSUE THREAD

**Issue by xyzvp** [2pocket2edition/Nukkit#20]
Expected: Let's say you built a portal at 1k, 1k, in theory you should come out at 7k7k / 8k8k
Actual: Small / low chance of coming out at 1k, 1k overworld (basically mirroring nether cords.

Reproduce bug: bad chunk render or poor connection / it randomly happening. I was travelling with WatsIToya2 and he appeared in mirrored nether cords.

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by DaMatrix** [comment]
Should be fixed in d2233d7177061fcb46a719e60b02f8463ff9f68a
