### ISSUE TITLE
MCPE enchanting

### ISSUE THREAD

**Issue by SafronMC** [2pocket2edition/Nukkit#21]
### Actual Behavior
Enchanting on mobile doesnt work. Plus the item that was to be enchanted disappears

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by TotherMeteor** [comment]
yeah, i had the same problem the item looms as if if its enchanted then when you select the item it goes in your iventory plain and if you try it again eventually it will disapear

**Comment by BaccaIsPopbob** [comment]
I faced the same issue just a few minutes ago. The item does in fact dissapear and you lose the lapis as well. However, enchanting continues work fine for win10 users

**Comment by DaMatrix** [comment]
Duplicated in #41 , so I'll close this for clarity's sake
