### ISSUE TITLE
TNT falling through floor when ignited

### ISSUE THREAD

**Issue by BaccaIsPopbob** [2pocket2edition/Nukkit#24]
### Expected Behavior

Tnt once ignited stays on the block below it and explodes

### Actual Behavior

Tnt falls through blocks and under the surface (nothing wrong with the explosions)

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by DaMatrix** [comment]
Duplicate of #7, closing
