### ISSUE TITLE
Death

### ISSUE THREAD

**Issue by JackNelo** [2pocket2edition/Nukkit#26]
When you die in the nether your items disappear forever

**Comment by JackNelo** [comment]
Oof

**Comment by BaccaIsPopbob** [comment]
This happens alot if you die on an obby walkway above lava perhaps it makes sense but you could be in the middle of a land mass and die and items just dissapear doesnt make sense

**Comment by DaMatrix** [comment]
Should be fixed as of dac184332b9751af8697f2dede0e5f663dc9c5a2 . thanks!
