### ISSUE TITLE
Beds Still Don't Work

### ISSUE THREAD

**Issue by BaccaIsPopbob** [2pocket2edition/Nukkit#35]
### Expected Behavior

Tap on the bed at night. Go into the sleep stage on the bed (if alone on tge server it goes to daytime)

### Actual Behavior

Not allowed to sleep in the bed and given the message "tile.bed.noSleep"

### Steps to Reproduce

Wait for night time. Try sleeping on bed by tapping

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by DaMatrix** [comment]
heh

**Comment by Airborne972** [comment]
@everyone

**Comment by Airborne972** [comment]
Sorry about that, also @TheDarkWolfOG#4400 it was *edited* because the ping I used on bricker didn’t work at first.

**Comment by Airborne972** [comment]
ChewieChewChew @TheDarkWolfOG#4400 **dont pay any attention here pls**

**Comment by DaMatrix** [comment]
why are you trying to use discord tags on github. also @everyone isn't a tag, you can't tag everyone. you literally just mentioned somebody named "everyone"
