### ISSUE TITLE
GitHub question, “ Can I comment on comments?”

### ISSUE THREAD

**Issue by Airborne972** [2pocket2edition/Nukkit#36]
### Expected Behavior
 I expected an answer 

### Actual Behavior
 so far I didn’t get one 

### Steps to Reproduce

Ask the question, then wait for it not to be answered 

### Debug information

* Debug link: https://youtube.com/
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by DaMatrix** [comment]
no
