### ISSUE TITLE
This is more of a physiological problem than a server problem I think. But how come that every time I call myself a veteran, that people call me a new faggot?

### ISSUE THREAD

**Issue by Airborne972** [2pocket2edition/Nukkit#37]
### Expected Behavior
 I expected people to believe meh

### Actual Behavior
 people called me a fag, and then cancerous when they realized it was a joke.

### Steps to Reproduce
 
1) Say I’m a veteran 
2) Wait for a response

### Debug information

* Debug link:
* Timings link (if relevant):
1) say it was a joke
2) everything is cool (usually)

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by DaMatrix** [comment]
shut the fuck up
