### ISSUE TITLE
FIX CHUNKS

### ISSUE THREAD

**Issue by brexmania123** [2pocket2edition/Nukkit#38]
### Expected Behavior

ALL CHUNKS to load correctly

### Actual Behavior

only about HALF of all the chunks load

### Steps to Reproduce

just by any traveling or by lagging in

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by DaMatrix** [comment]
i haven't been able to reproduce anything of the sort myself, sorry
