### ISSUE TITLE
Gaps

### ISSUE THREAD

**Issue by BaccaIsPopbob** [2pocket2edition/Nukkit#39]
### Expected Behavior

Once the enchated golden apple is eaten, you get 5 mins of fire resistance and resistance each, 30 seconds of regeneration V, and 2 mins of Absorption hearts. You also get two hunger bars if hungry.

### Actual Behavior

Enchanted golden apple is only visually eated but returns to the inventory right after being "eaten". Hunger bars you regain is also only visual as you never actually ate the apple. As a result you get no hunger or effects.

### Steps to Reproduce

Simply craft an Enchabted Golden Apple and attenpt to eat it.

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by BaccaIsPopbob** [comment]
Alright theres an issue posted now to wait *dies next day*

**Comment by DaMatrix** [comment]
possibly fixed in cdd30dd1 ? pls test

**Comment by Legit4K** [comment]
Nope, still broken

**Comment by DaMatrix** [comment]
Closing all issues due to pending update to NukkitX 2.0
