### ISSUE TITLE
EOF can leak bases

### ISSUE THREAD

**Issue by brexmania123** [2pocket2edition/Nukkit#40]
### Expected Behavior

Some times on the server a message appears that resets or tries to reload a chunk.

### Actual Behavior

![image](https://user-images.githubusercontent.com/25558762/43982089-b816bab6-9cb1-11e8-91d3-deefbd9bb22d.png)

### Steps to Reproduce

occasionally appears in chat

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by DaMatrix** [comment]
should be fixed as of 70c5643e
