### ISSUE TITLE
What the server still needs

### ISSUE THREAD

**Issue by jacknelosaysre** [2pocket2edition/Nukkit#41]
- [x] 1. Structure generation (Strongholds, Dungeons, Villages, Ocean monuments, etc.)
- [x] 2. withers
- [ ] 3. there is a visual glitch when lavacasting that makes you have to relog
- [ ] 4. there is glowstone that spawns at max height in nether or the top bedrock layer so you can destroy that and see above the nether roof 
- [ ] 5. Villagers and emeralds to mine so you can trade with them
- [ ] 6. Enchantments for phones
- [ ] 7. All of the items that are possible to obtain in game should be added and than i or the community can tell you whats wrong with the item or items
- [ ] 8. Mobs on top of the nether roof and lightning on top of the nether roof
- [ ] 9. When you die and hit main menu you are where you were before you died so patch that
- [x] 10. Arrows don't explode end crystals so make that work
-11. There is a new dupe idk of yet but there is 1
Ill make or add on to this one later when i can think a bit more but this is all i can think of for now-JackNelo

**Comment by DaMatrix** [comment]
1. Will have to hold off until I finish my generator rewrite
5. Also rewrite
6. There's no other reasonable way of making enchantment work on phones atm afaik, I'll give it another look though
7. Can I have a list? (with checkboxes pls :P)
9. Holy shit, since when has that been a thing? Pritority: urgent
10. End crystals aren't implemented serverside and shouldn't even be obtainable, so no(t yet)

**Comment by o0ZzM4g1c** [comment]
6. Enchantments for Phones >> 6. Enchantments for **Android**
...as it's working well on iOS.

11 - Use hoppers with furnace (not part of redstone)
12 - Stack all kinds of leaves (not oak only)
![image](https://user-images.githubusercontent.com/43145135/45308870-bf6e6a00-b522-11e8-8f9e-8e185242be9b.png)

**Comment by jacknelosaysre** [comment]
End crystals are no longer working

**Comment by jacknelosaysre** [comment]
Well they are but they crash the server

**Comment by jacknelosaysre** [comment]
Can you make thorns less powerful, it kills the attacker and does a shit ton of damage

**Comment by bowlz1** [comment]
In other words thorns damage ignores armor, so a naked player takes the same damaga as someone wearing prot4

**Comment by o0ZzM4g1c** [comment]
The arrows drawn by the skeletons pass through the walls (one block thickness). And you die.
Observed with:
- Glass wall
- Wooden wall

**Comment by DaMatrix** [comment]
Closing all issues due to pending update to NukkitX 2.0
