### ISSUE TITLE
Beds Not Working 

### ISSUE THREAD

**Issue by Rcb1235** [2pocket2edition/Nukkit#43]
### Expected Behavior

After clicking on a bed, your spawnpoint should be updated. It should stay updated after the player logs out, then logs back in. 

### Actual Behavior

After clicking on a bed, the 'Updated spawn point!' msg is shown. The bed works as intended unless the player relogs. After reloging the bed will not respawn you beside it, you will respawn back at spawn.

### Steps to Reproduce

1. Obtain a bed

2. Click it 

3. Relog

4. Kill your self (I tryed a bunch of different ways with the same result)

5. You will be respawned at spawn instead of by your bed

### Debug information

null

### Crashdump, Backtrace or Other Files

null

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error

**Comment by Rcb1235** [comment]
Beds still dont work as intended.

**Comment by RoyalDragon20** [comment]
Current dupes and tp needs to be patched

**Comment by DaMatrix** [comment]
Closing all issues due to pending update to NukkitX 2.0
