### ISSUE TITLE
overworld dimension fail when changing world nether > OW

### ISSUE THREAD

**Issue by o0ZzM4g1c** [2pocket2edition/Nukkit#44]
### Expected Behavior

When player switch world from nether to overworld, the world dimension is updated to overworld dimension (Y0 -> Y256)

### Actual Behavior

When player go through a portal from the nether to overworld: the sky remain red (known issue) but either the world height dimension remain Y128.
Player get instant suffocation damage if climb up over Y128
Relog solve the problem
Platform: iOS and W10

### Steps to Reproduce

Travel from nether into overworld by portals until get the red sky glitch

### Linked NukkitX issue
https://github.com/NukkitX/Nukkit/issues/543

**Comment by DaMatrix** [comment]
does the player actually die of suffocation? if not, then it's a client issue.

**Comment by o0ZzM4g1c** [comment]
Yes, he dies after some seconds

**Comment by o0ZzM4g1c** [comment]
Any news on that ? It happened to me again 3 days ago at spawn.

**Comment by DaMatrix** [comment]
ok, i'll look into this again.

the sky is a bug with mcpe, even a number of featured servers have this issue.

**Comment by DaMatrix** [comment]
for now i'd recommend relogging after changing dimensions, just to make sure.

**Comment by o0ZzM4g1c** [comment]
Also another issue linked to this:

Go through a portal OW at Y level >128, kills you instantly, because you pop in nether over the ceiling. So world dimensions aren’t converted.

**Comment by DaMatrix** [comment]
now **that** is an easy fix

**Comment by DaMatrix** [comment]
ok, that issue is now fixed in 8532c4bce45e812f2878ab82d5054c5b667ac8cc

next time please make things like that as a separate issue, it makes it a lot easier to keep track of :P

**Comment by DaMatrix** [comment]
Closing all issues due to pending update to NukkitX 2.0
