### ISSUE TITLE
lost enchants after cancel connection

### ISSUE THREAD

**Issue by o0ZzM4g1c** [2pocket2edition/Nukkit#47]
### Expected Behavior

Keep all enchanted stuff even after several connection issues

### Actual Behavior

Lost enchants on all owned stuff, armor, weapons etc... even in echest.
https://streamable.com/wf6ws

### Steps to Reproduce

- display server list on mcpe
- touch/clic 2p2e server
- CANCEL connection in less a second
- re-connect to 2p2e
 —> enchants gone

**Comment by DaMatrix** [comment]
Closing all issues due to pending update to NukkitX 2.0
